# ------------------------------------------------------------------------------
# my-roles/my_mta/handlers/main.yml
# ------------------------------------------------------------------------------

# NOTE: We must use include_tasks not import_tasks in handlers in the roles
# within the my-role directory, otherwise the handlers they define are not
# visible to the roles within the libraries-ansible directory.

---

- ansible.builtin.command: update-exim4.conf
  listen: Exim configuration changed

- ansible.builtin.include_tasks: stop-exim.yml
  listen: Exim configuration changed

- ansible.builtin.include_tasks: start-exim.yml
  listen: Exim configuration changed
