# ------------------------------------------------------------------------------
# my-roles/my_backup_storage/tasks/main.yml
# ------------------------------------------------------------------------------

---

- ansible.builtin.import_role:
    name: /libraries-ansible_roles/backup

- ansible.builtin.import_role:
    name: /libraries-ansible_roles/backup_storage
    tasks_from: install-service
    handlers_from: none

- ansible.builtin.import_role:
    name: /libraries-ansible_roles/backup_storage
    tasks_from: configure-service
    handlers_from: none
