# my-roles/tasks/main.yml
---

- ansible.builtin.import_role:
    name: /libraries-ansible_roles/backup

- ansible.builtin.import_role:
    name: /libraries-ansible_roles/backup_client
    tasks_from: install-service
    handlers_from: none

- ansible.builtin.import_tasks:
    file: start-bacula-fd.yml

- ansible.builtin.import_role:
    name: /libraries-ansible_roles/backup_client
    tasks_from: configure-service
    handlers_from: none
