# ------------------------------------------------------------------------------
# my-roles/my_calendar/tasks/start-radicale.yml
# ------------------------------------------------------------------------------

---

- name: Get the codename of the Debian release on this host
  ansible.builtin.command: lsb_release --codename --short
  register: lsb_release
  changed_when: false

- name: Test if the radicale process is running
  ansible.builtin.shell: |-
    {% if lsb_release.stdout == 'buster' %}
    pgrep -f '^/usr/bin/python3 /usr/bin/radicale -f$'
    {% elif lsb_release.stdout == 'bullseye' %}
    pgrep -f '^/usr/bin/python3 /usr/bin/radicale$'
    {% endif %}
  register: pgrep_result
  changed_when: false
  failed_when: pgrep_result.rc != 0 and pgrep_result.rc != 1

- block:

    - name: Start the radicale process
      ansible.builtin.shell: |-
        echo 'radicale   : Starting' >> /var/local/services.log
        {% if lsb_release.stdout == 'buster' %}
        nohup radicale -f |& sed -u 's/^/radicale   : /' \
          &>> /var/local/services.log &
        {% elif lsb_release.stdout == 'bullseye' %}
        nohup radicale |& sed -u 's/^/radicale   : /' \
          &>> /var/local/services.log &
        {% endif %}
      args:
        executable: /bin/bash
      become: yes

    - name: Check the radicale process has started
      # We do this in a separate shell task to the one that we started the
      # process in so that we know that the process survived beyond that shell.
      ansible.builtin.shell: |
        n=0
        while [ $n -lt 3 ]; do
          sleep 3
          {% if lsb_release.stdout == 'buster' %}
          pgrep -f '^/usr/bin/python3 /usr/bin/radicale -f$' && \
            echo 'radicale   : Started' >> /var/local/services.log && break
          {% elif lsb_release.stdout == 'bullseye' %}
          pgrep -f '^/usr/bin/python3 /usr/bin/radicale$' && \
            echo 'radicale   : Started' >> /var/local/services.log && break
          {% endif %}
          let n=n+1
        done

        if [ $n -eq 3 ]; then
          echo 'radicale   : Failed to start process' \
            >> /var/local/services.log
          exit 1
        fi
      args:
        executable: /bin/bash

  when: pgrep_result.rc == 1
