# ------------------------------------------------------------------------------
# my-roles/my_dns_client/tasks/main.yml
# ------------------------------------------------------------------------------

---

- ansible.builtin.import_role:
    name: /libraries-ansible_roles/dns_client
  vars:
    unsafe_writes: true
